### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by minhtri22** [stelace/marketplace-demo#496]
Hi, I have install api server as well as marketplace demo as instruction, everything work well and when I ran the "yarn dev" the website is loaded with message 401 unauthorized listed as below:
- config
- entries
- categories
<img width="365" alt="401" src="https://user-images.githubusercontent.com/10519160/122857798-4a6f2680-d343-11eb-8752-db4b738c5e16.PNG">

**Comment by woyuen** [comment]
Hi @minhtri22, it seems all your requests to API server failed due to authorization.

Did you fill the environment variables (`STELACE_PUBLISHABLE_API_KEY`, `STELACE_SECRET_API_KEY`) related to api keys that are generated by server seeding step (`yarn seed` in the [server project](https://github.com/stelace/stelace#run-server)) ?

**Comment by minhtri22** [comment]
Hi, thank you your reply. I have filled those generated keys from api server into the market-demo

**Comment by woyuen** [comment]
Glad it helped!
Please note the applications don't require `sudo` so it should have worked even without adding it.

**Comment by lirongliu** [comment]
Hi, I still get 401 after filling those generated keys..
